<?php
$z[0]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        <li class=\"line\">|</li>\r\n        ",275,434);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",544,566);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",582,607);
$z[2][4]['name']="cfg_adress";
$z[3]=Array("global","",625,651);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",652,676);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",869,891);
$z[5][4]['name']="cfg_tel";

?>