<?php
$z[0]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        <li class=\"line\">|</li>\r\n        ",275,434);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",542,564);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",580,605);
$z[2][4]['name']="cfg_adress";
$z[3]=Array("global","",623,649);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",650,674);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",867,889);
$z[5][4]['name']="cfg_tel";

?>